#ifndef _GE_CONSTANTS_HEADER_
#define	_GE_CONSTANTS_HEADER_

#define	GE_FRAME_RATE	30

#define GE_SCREEN_WIDTH 	640
#define GE_SCREEN_HEIGHT 	480 
#define GE_SCREEN_BPP 		32
#define GE_SCREEN_FLAGS		SDL_SWSURFACE | SDL_DOUBLEBUF
#define	GE_SCREEN_MAX_PLANES 	4

#define	GE_SPRITE_MAX_FRAMES	256
#define	GE_CHARACTER_LIMIT		256

#define	GE_COLORKEY_R	0x00
#define GE_COLORKEY_G	0xFF
#define GE_COLORKEY_B	0x00

#define	GE_COLLISIONMASK_R	0xFF
#define GE_COLLISIONMASK_G	0x00
#define	GE_COLLISIONMASK_B	0x00

#define GE_PLANE_MAX_OBJECTS 256

#define	GE_PLANEMAP_MAX_TILES	256

// Bellow values in tiles (default tile = 16x16)
#define GE_PLANEMAP_MAX_HEIGHT	1024
#define	GE_PLANEMAP_MAX_WIDTH	1024

#define	GE_DEFAULT_TILE_SIZE	16


enum GESpriteActionCtrl
{
	GE_SPRITE_ACTION_END		=-1,
	GE_SPRITE_ACTION_REPEAT		=-2,
	GE_SPRITE_ACTION_INITREP	=-3
};

//typedef int* GESpriteAction;
#define GESpriteAction int*

enum GESpriteDirection
{
	GE_SPRITE_FACING_RIGHT		=0,
	GE_SPRITE_FACING_LEFT		=1
};

enum GEAction
{
	GE_ACTION_STANDING		=0x00000000,
	GE_ACTION_MOVING_LEFT	=0x00000001,
 	GE_ACTION_MOVING_RIGHT	=0x00000002,
	GE_ACTION_JUMPING		=0x00000010,
	GE_ACTION_FALLING		=0x00000020,
	GE_ACTION_DASHING		=0x00000100,
	GE_ACTION_ATTACKING		=0x00001000,
	GE_ACTION_TELEPORT_IN	=0x00010000,
	GE_ACTION_TELEPORT_LAND =0x00020000,
	GE_ACTION_TELEPORT_OUT	=0x00040000
};

enum GECollisionType
{
	 GE_COLLISION_SOLID = 0,
	 GE_COLLISION_SEMISOLID,
	 GE_COLLISION_LIQUID,
	 GE_COLLISION_GASOSE,
	 GE_COLLISION_NONE
};



#endif // _GE_CONSTANTS_HEADER_
